version: '3'

services:
  product-back:
    build: 
      context: .
      dockerfile: ./services/product/backend/cmd/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
  product-front:
    build:
      context: .
      dockerfile: ./services/product/frontend/Dockerfile
    volumes:
      - ./share:/app/share
    ports:
      - "8081:8081"
  organization-front:
    build:
      context: .
      dockerfile: ./services/organization/frontend/Dockerfile
    volumes: 
      - ./share:/app/share
    ports:
      - "8082:8082"
  account-front:
    build:
      context: .
      dockerfile: ./services/account/frontend/Dockerfile
    volumes:
      - ./share:/app/share
    ports:
      - "8083:8083"
  employee-front:
    build:
      context: .
      dockerfile: ./services/employee/frontend/Dockerfile
    volumes:
      - ./share:/app/share
    ports:
      - "8084:8084"
  customer-front:
    build: 
      context: .
      dockerfile: ./services/customer/frontend/Dockerfile
    volumes:
      - ./share:/app/share
    ports:
      - "8085:8085"
  proxy-front:
    build:
      context: .
      dockerfile: ./services/proxy/frontend/Dockerfile
    volumes: 
      - ./share:/app/share
    ports:
      - "8086:8086"
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: proxy_db
    ports:
      - "5432:5432"